version: "3.8"

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"

    app1:
        environment:
            - FLASK_APP=app1/app
        build:
            context: .
            dockerfile: app1.Dockerfile
        ports:
            - "8001:8001"
        command: pdm run flask run --host 0.0.0.0 --port 8001

    app2:
        environment:
            - FLASK_APP=app2/app
        build:
            context: .
            dockerfile: app2.Dockerfile
        ports:
            - "8002:8002"
        command: pdm run flask run --host 0.0.0.0 --port 8002

    app3:
        environment:
            - FLASK_APP=app3/app
        build:
            context: .
            dockerfile: app3.Dockerfile
        ports:
            - "8003:8003"
        command: pdm run flask run --host 0.0.0.0 --port 8003
