version: "3.8"

services:

    nginx:
        build: .
        ports:
            - "80:80"

    flask-app:
        build:
            context: ./flask-app
            dockerfile: Dockerfile
        ports:
            - "7000:7000"
        command: pdm run flask run --host=0.0.0.0 --port=7000


    django-app:
        build:
            context: ./django-app
            dockerfile: Dockerfile
        ports:
            - "8000:8000"

        command: pdm run python testpro/manage.py runserver 0.0.0.0:8000
